#pragma once
#include "../Project.h"



// set all GPIOs to a defined default state
void GPIO_SetToDefaultState()
{
	GPIO_SetPin(BUFF_OE_A,	GPIO_HIGH);
	GPIO_SetPin(BUFF_OE_B,	GPIO_HIGH);
	GPIO_SetPin(BUFF_OE_C,	GPIO_HIGH);
	GPIO_SetPin(CS_A,		GPIO_HIGH);
	GPIO_SetPin(CS_B,		GPIO_HIGH);
	GPIO_SetPin(CS_C,		GPIO_HIGH);
	GPIO_SetPin(DEBUG_PIN,	GPIO_LOW);
	GPIO_SetPin(CPU_BUSY, 	GPIO_LOW);
}

void GPIO_SetToTemperatureReading()
{
	GPIO_SetPin(BUFF_OE_A,	GPIO_LOW);
	GPIO_SetPin(BUFF_OE_B,	GPIO_LOW);
	GPIO_SetPin(BUFF_OE_C,	GPIO_LOW);
	GPIO_SetPin(CS_A,		GPIO_LOW);
	GPIO_SetPin(CS_B,		GPIO_LOW);
	GPIO_SetPin(CS_C,		GPIO_LOW);
	GPIO_SetPin(ADC_IO_A,	GPIO_HIGH);
	GPIO_SetPin(ADC_IO_B,	GPIO_HIGH);
	GPIO_SetPin(ADC_IO_C,	GPIO_HIGH);
}


// Set Pin as GPIO and write state
void GPIO_SetPin(int gpio, int state)
{
	if((state != GPIO_LOW) && (state != GPIO_HIGH))
		ESTOP0;	// Error: invalid GPIO state

	GPIO_SetupPinMux(gpio, GPIO_MUX_CPU1, 0);
	GPIO_SetupPinOptions(gpio, GPIO_OUTPUT, GPIO_PUSHPULL);
	GPIO_WritePin(gpio, state);
}

// Code generated by TI Pin MUX TOOL
void GPIO_SetPinMux()
{
    Uint32 lockValA;
    Uint32 lockValB;
    Uint32 lockValC;
    Uint32 lockValD;

    EALLOW;

    // Save the current value of the GPIO lock registers
    lockValA = GpioCtrlRegs.GPALOCK.all;
    lockValB = GpioCtrlRegs.GPBLOCK.all;
    lockValC = GpioCtrlRegs.GPCLOCK.all;
    lockValD = GpioCtrlRegs.GPDLOCK.all;


    // Unlock the GPIO control registers
    GpioCtrlRegs.GPALOCK.all = 0x00000000;
    GpioCtrlRegs.GPBLOCK.all = 0x00000000;
    GpioCtrlRegs.GPCLOCK.all = 0x00000000;
    GpioCtrlRegs.GPDLOCK.all = 0x00000000;


    // Clear the mux register fields that are about to be changed
    GpioCtrlRegs.GPAMUX1.all	&= ~GPAMUX1_MASK;
    GpioCtrlRegs.GPAMUX2.all	&= ~GPAMUX2_MASK;
    GpioCtrlRegs.GPAGMUX1.all	&= ~GPAMUX1_MASK;
    GpioCtrlRegs.GPAGMUX2.all	&= ~GPAMUX2_MASK;
    GpioCtrlRegs.GPBMUX1.all	&= ~GPBMUX1_MASK;
    GpioCtrlRegs.GPBMUX2.all	&= ~GPBMUX2_MASK;
    GpioCtrlRegs.GPBGMUX1.all	&= ~GPBMUX1_MASK;
    GpioCtrlRegs.GPBGMUX2.all	&= ~GPBMUX2_MASK;
    GpioCtrlRegs.GPCMUX1.all	&= ~GPCMUX1_MASK;
    GpioCtrlRegs.GPCMUX2.all	&= ~GPCMUX2_MASK;
    GpioCtrlRegs.GPCGMUX1.all	&= ~GPCMUX1_MASK;
    GpioCtrlRegs.GPCGMUX2.all	&= ~GPCMUX2_MASK;
    GpioCtrlRegs.GPDMUX1.all	&= ~GPDMUX1_MASK;
    GpioCtrlRegs.GPDGMUX1.all	&= ~GPDMUX1_MASK;


    // Write pin muxing to mux registers
    GpioCtrlRegs.GPAGMUX1.all	|=  GPAGMUX1_VALUE;
    GpioCtrlRegs.GPAGMUX2.all	|=  GPAGMUX2_VALUE;
    GpioCtrlRegs.GPAMUX1.all	|=  GPAMUX1_VALUE;
    GpioCtrlRegs.GPAMUX2.all	|=  GPAMUX2_VALUE;
    GpioCtrlRegs.GPBGMUX1.all	|=  GPBGMUX1_VALUE;
    GpioCtrlRegs.GPBGMUX2.all	|=  GPBGMUX2_VALUE;
    GpioCtrlRegs.GPBMUX1.all	|=  GPBMUX1_VALUE;
    GpioCtrlRegs.GPBMUX2.all	|=  GPBMUX2_VALUE;
    GpioCtrlRegs.GPCGMUX1.all	|=  GPCGMUX1_VALUE;
    GpioCtrlRegs.GPCGMUX2.all	|=  GPCGMUX2_VALUE;
    GpioCtrlRegs.GPCMUX1.all	|=  GPCMUX1_VALUE;
    GpioCtrlRegs.GPCMUX2.all	|=  GPCMUX2_VALUE;
    GpioCtrlRegs.GPDGMUX1.all	|=  GPDGMUX1_VALUE;
    GpioCtrlRegs.GPDMUX1.all	|=  GPDMUX1_VALUE;


    // Write pin analog mode select to registers
    GpioCtrlRegs.GPBAMSEL.all	&= ~GPBAMSEL_MASK;
    GpioCtrlRegs.GPBAMSEL.all	|= GPBAMSEL_VALUE;


    // Restore GPIO lock register values
    GpioCtrlRegs.GPALOCK.all = lockValA;
    GpioCtrlRegs.GPBLOCK.all = lockValB;
    GpioCtrlRegs.GPCLOCK.all = lockValC;
    GpioCtrlRegs.GPDLOCK.all = lockValD;

    EDIS;
}
// Genereted Code END


